#!/usr/bin/env python3
# a simplified version of the approve key script, that bypasses the steam client for the hackendeck setup

import sys
import subprocess
import json
import logging

logging.basicConfig(level=logging.INFO, format='%(message)s')
LOG = logging.getLogger(__name__)

if __name__ == '__main__':
    request = open(sys.argv[1], 'rt').read()
    requestIP = 'Unknown'
    try:
        requestIP = sys.argv[2]
    except NameError:
        LOG.warning('request IP not given as argument to hook')
        pass

    key_identifier = request.split(' ')[2]
    prompt = f'Approve pairing request from {requestIP} {key_identifier!r} ?'
    cmd = ['zenity', '--question', '--text', prompt, '--ok-label', 'Approve', '--cancel-label', 'Deny', '--timeout=10']
    LOG.info(cmd)
    cp = subprocess.run(cmd)

    ret = {}
    if cp.returncode != 0:
        ret['error'] = 'denied'
    print(json.dumps({}))

    sys.exit(cp.returncode)