#!/bin/bash

set -o pipefail
shopt -s failglob
set -u

TOP_FOLDER="$(cd $(dirname $0) && echo $PWD)"
${TOP_FOLDER}/configure-hackendeck.py || exit 1
HOOKS_FOLDER=${TOP_FOLDER}/hooks
exec konsole -e ${TOP_FOLDER}/steamos-devkit-service.py --hooks ${HOOKS_FOLDER}

